[project]
name = "candle"
version = "0.0.1"
description = "Utilities for PyTorch"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [
  {name = "Hangeer", email = "hangeerh@sina.com"}
]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.5.1",
    "torch>=2.13.0",
]
keywords = ["utility", "pytorch"]

[project.urls]
Homepage = "https://github.com/Hangeerh/candle"
Issues = "https://github.com/Hangeerh/candle/issues"

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pytest>=9.1.1",
    "ruff>=0.15.21",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["/candle"]

[tool.ruff]

# Check for docstring line too long
lint.select = ["W505"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 100
